version: "3.9"
services:
  gateway:
    build: ../gateway
    image: gateway
    container_name: gateway
    ports:
      - "8081:8081"
  
  auth-ms:
    build: ../auth-ms
    image: auth-ms
    container_name: auth-ms
    depends_on:
      - "auth_db"
    ports:
      - "8082:8082"

  accommodation-ms:
    build: ../accommodation-ms
    image: accommodation-ms
    container_name: accommodation-ms
    depends_on:
      - "accommodation_db"
    ports:
      - "8083:8083"
  
  reservation-ms:
    build: ../reservation-ms
    image: reservation-ms
    container_name: reservation-ms
    depends_on:
      - "reservation_db"
    ports:
      - "8084:8084"

  auth_db:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth
    ports:
      - "3307:3306"
  
  accommodation_db:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=accommodation
    ports:
      - "3309:3306"
  
  reservation_db:
    image: "mongo:4.4.3"
    restart: always

  recommendation_db:
    image: neo4j:5.8.0
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

