version: "3.9"
services:
  discovery:
    build: ../discovery
    image: discovery
    container_name: discovery
    ports:
      - "8761:8761"
  gateway:
    build: ../gateway
    image: gateway
    container_name: gateway
    ports:
      - "8081:8081"
    environment:
      - "eureka.client.serviceUrl.defaultZone= http://discovery:8761/eureka"
  auth-ms:
    build: ../auth-ms
    image: auth-ms
    container_name: auth-ms
    depends_on:
      - "auth_db"
    ports:
      - "8082:8082"
    environment:
      - "eureka.client.serviceUrl.defaultZone= http://discovery:8761/eureka"
  accommodation-ms:
    build: ../accommodation-ms
    image: accommodation-ms
    container_name: accommodation-ms
    depends_on:
      - "accommodation_db"
    ports:
      - "8083:8083"
    environment:
      - "eureka.client.serviceUrl.defaultZone= http://discovery:8761/eureka"
  reservation-ms:
    build: ../reservation-ms
    image: reservation-ms
    container_name: reservation-ms
    ports:
      - "8084:8084"
    environment:
      - "eureka.client.serviceUrl.defaultZone= http://discovery:8761/eureka"
  auth_db:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth
    ports:
      - "3307:3306"
  accommodation_db:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=accommodation
    ports:
      - "3309:3306"
