global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8081']
        labels:
          application: 'Gateway Service Application'
  - job_name: 'accommodation-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['accommodation-ms:8083']
        labels:
          application: 'Accommodation Service Application'
  - job_name: 'auth-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-ms:8082']
        labels:
          application: 'Auth Service Application'
  - job_name: 'reservation-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reservation-ms:8084']
        labels:
          application: 'Reservation Service Application'
  - job_name: 'recommendation-ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['recommendation-ms:8085']
        labels:
          application: 'Recommendation Service Application'